<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql

--cohort analysis with MIN()
WITH yearlycohort AS
(select distinct
customerkey,
EXTRACT(year from min(orderdate) over (partition by customerkey)) as cohort_year
from sales
)
select cohort_year,
extract(year from orderdate) as purchase_year,
sum(s.quantity * s.netprice * s.exchangerate) as net_rev
from sales s
left join yearlycohort y on s.customerkey = y.customerkey
group by cohort_year,extract(year from orderdate)
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

   cohort_year purchase_year     net_rev
0         2015          2015  7370979.48
1         2015          2016   392623.48
2         2015          2017   479841.31
3         2015          2018  1069850.87
4         2015          2019  1235991.48
5         2015          2020   386489.60
6         2015          2021   872845.99
7         2015          2022  1569787.72
8         2015          2023  1157633.91
9         2015          2024   356186.62
10        2016          2016  9990990.20
11        2016          2017   497028.11
12        2016          2018  1074607.29
13        2016          2019  1565400.72
14        2016          2020   474087.09
15        2016          2021   964417.85
16        2016          2022  2164681.10
17        2016          2023  1265242.63
18        2016          2024   364066.76
19        2017          2017 12244469.63

In [9]:
%%sql
--cohort analysis with count()--unque customers per year by cohort
WITH cohort_purchase_year AS (
  select customerkey,
EXTRACT(year from min(orderdate) over (partition by customerkey)) as cohort_year,
extract(year from orderdate) as purchase_year
from sales)
SELECT cohort_year,
purchase_year,
count(distinct customerkey) as customers
from cohort_purchase_year
group by cohort_year,purchase_year
order by cohort_year,purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  customers
0         2015          2015       2825
1         2015          2016        126
2         2015          2017        149
3         2015          2018        348
4         2015          2019        388
5         2015          2020        171
6         2015          2021        295
7         2015          2022        600
8         2015          2023        499
9         2015          2024        146
10        2016          2016       3397
11        2016          2017        174
12        2016          2018        374
13        2016          2019        457
14        2016          2020        205
15        2016          2021        336
16        2016          2022        746
17        2016          2023        573
18        2016          2024        183
19        2017          2017       4068
20        2017          2018        473
21        2017          2019        570
22        2017          2020        251
23        2017          2021        450
24        2017          2022        943
25        2017          2023        738
26        2017          2024        246
27        2018          2018       7446
28        2018          2019       1081
29        2018          2020        475
30        2018          2021        779
31        2018          2022       1644
32        2018          2023       1407
33        2018          2024        426
34        2019          2019       7755
35        2019          2020        523
36        2019          2021        873
37        2019          2022       1700
38        2019          2023       1439
39        2019          2024        370
40        2020          2020       3031
41        2020          2021        358
42        2020          2022        694
43        2020          2023        547
44        2020          2024        163
45        2021          2021       4663
46        2021          2022       1051
47        2021          2023        889
48        2021          2024        268
49        2022          2022       9010
50        2022          2023       1764
51        2022          2024        561
52        2023          2023       5890
53        2023          2024        332
54        2024          2024       1402

In [16]:
%%sql
--cohort analysis with count()--unque customers per year by cohort
WITH cohort_purchase_year AS (
  select distinct customerkey,
EXTRACT(year from (min(orderdate) over (partition by customerkey))) as cohort_year,
extract(year from orderdate) as purchase_year
from sales)
SELECT distinct
 cohort_year,
purchase_year,
count(customerkey) over (partition by purchase_year, cohort_year) as customers
from cohort_purchase_year
order by cohort_year,purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  customers
0         2015          2015       2825
1         2015          2016        126
2         2015          2017        149
3         2015          2018        348
4         2015          2019        388
5         2015          2020        171
6         2015          2021        295
7         2015          2022        600
8         2015          2023        499
9         2015          2024        146
10        2016          2016       3397
11        2016          2017        174
12        2016          2018        374
13        2016          2019        457
14        2016          2020        205
15        2016          2021        336
16        2016          2022        746
17        2016          2023        573
18        2016          2024        183
19        2017          2017       4068
20        2017          2018        473
21        2017          2019        570
22        2017          2020        251
23        2017          2021        450
24        2017          2022        943
25        2017          2023        738
26        2017          2024        246
27        2018          2018       7446
28        2018          2019       1081
29        2018          2020        475
30        2018          2021        779
31        2018          2022       1644
32        2018          2023       1407
33        2018          2024        426
34        2019          2019       7755
35        2019          2020        523
36        2019          2021        873
37        2019          2022       1700
38        2019          2023       1439
39        2019          2024        370
40        2020          2020       3031
41        2020          2021        358
42        2020          2022        694
43        2020          2023        547
44        2020          2024        163
45        2021          2021       4663
46        2021          2022       1051
47        2021          2023        889
48        2021          2024        268
49        2022          2022       9010
50        2022          2023       1764
51        2022          2024        561
52        2023          2023       5890
53        2023          2024        332
54        2024          2024       1402

In [27]:
%%sql
--window functions and group by..best to not combine but treat differently
--customer lifetime value
WITH yearly_cohort AS (select customerkey,
EXTRACT(year from (min(orderdate))) as cohort_year,
sum(s.quantity * s.netprice * s.exchangerate) as clt_value
from sales s
group by customerkey)

select *,
avg(clt_value) over (partition by cohort_year) as avg_clt
from yearly_cohort

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  clt_value  avg_clt
0          1916173        2015    1042.98  5271.59
1           938590        2015    4627.27  5271.59
2          1807995        2015    1434.21  5271.59
3          1401105        2015    8773.13  5271.59
4          2097053        2015    1726.44  5271.59
...            ...         ...        ...      ...
49482       798336        2024    1669.66  2037.55
49483       792005        2024    2014.00  2037.55
49484       821211        2024    1481.27  2037.55
49485      1778597        2024    5963.31  2037.55
49486      1659563        2024    5734.22  2037.55

[49487 rows x 4 columns]

In [29]:
%%sql
--filtering with where
--use where to filter rows before aggregation
--cohort year analysis > 2020
select customerkey,
EXTRACT(year from (min(orderdate) over (partition by customerkey))) as cohort_year
from sales
where extract(year from orderdate) > 2020

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

113184 rows affected.

        customerkey cohort_year
0                15        2021
1               180        2023
2               180        2023
3               387        2021
4               387        2021
...             ...         ...
113179      2099697        2022
113180      2099697        2022
113181      2099743        2022
113182      2099743        2022
113183      2099743        2022

[113184 rows x 2 columns]

In [ ]:
%%sql
--use where to filter data after window functions
WITH data AS
 (select columnname,
window function() over (partition by columnname) as wfc
from tablename)
select *
from data
where wfc > 10 use where after windows function;

In [47]:
%%sql
--windw function - ranking
select
customerkey, orderdate,
(quantity * netprice * exchangerate) as net_rev,
rank() over (partition by customerkey order by (quantity * netprice * exchangerate) desc) as rank
from sales
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

    customerkey   orderdate  net_rev  rank
0            15  2021-03-08  2217.41     1
1           180  2023-08-28  1913.55     1
2           180  2018-07-28   525.31     2
3           180  2023-08-28    71.36     3
4           185  2019-06-01  1395.52     1
5           243  2016-05-19   287.67     1
6           387  2018-12-21  1608.10     1
7           387  2021-10-30  1265.56     2
8           387  2018-12-21   619.77     3
9           387  2023-11-16   446.44     4
10          387  2023-11-16   362.44     5
11          387  2023-11-16   180.35     6
12          387  2018-12-21    97.05     7
13          387  2018-12-21    45.62     8
14          387  2023-11-16    30.51     9
15          406  2021-11-06  1430.73     1
16          406  2021-11-06   762.69     2
17          545  2023-07-01  1475.91     1
18          545  2023-07-01  1344.62     2
19          545  2023-07-01   318.67     3

In [34]:
%%sql
select
customerkey, orderdate,
(quantity * netprice * exchangerate) as net_rev,
count(*) over (partition by customerkey order by orderdate
) as runingorder_count,
avg((quantity * netprice * exchangerate)) over (partition by customerkey order by orderdate
) as runingorder_avg
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey   orderdate  net_rev  runingorder_count  runingorder_avg
0                15  2021-03-08  2217.41                  1          2217.41
1               180  2018-07-28   525.31                  1           525.31
2               180  2023-08-28    71.36                  3           836.74
3               180  2023-08-28  1913.55                  3           836.74
4               185  2019-06-01  1395.52                  1          1395.52
...             ...         ...      ...                ...              ...
199868      2099711  2016-08-13  2067.75                  1          2067.75
199869      2099711  2017-08-14  3940.92                  2          3004.34
199870      2099743  2022-03-17   375.57                  2           234.81
199871      2099743  2022-03-17    94.05                  2           234.81
199872      2099743  2023-02-11   598.46                  3           356.03

[199873 rows x 5 columns]

In [48]:
%%sql
--row_number() and order by
select
row_number() over(partition by orderdate order by orderdate, orderkey, linenumber) as rownum,
*
from sales;

--using where to filter
with row_numbering AS (select
row_number() over(partition by orderdate order by orderdate, orderkey, linenumber) as rownum,
*
from sales)
select *
from row_numbering
where rownum > 1;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

196579 rows affected.

,rownum,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
1,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
2,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
3,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
4,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196574,93,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
196575,94,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
196576,95,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
196577,96,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
196578,97,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [3]:
%%sql
--using row_number(), rank() and dense_rank()
--ranking customer order quantity
select
customerkey,
count(*) as totalorder_count,
row_number() over (order by count(*) desc) as totalorder_rownum,
rank() over (order by count(*) desc) as totalorder_rank,
dense_rank() over (order by count(*) desc) as totalorder_dense_rank
from sales
group by customerkey
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,totalorder_count,totalorder_rownum,totalorder_rank,totalorder_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,1495941,26,4,4,4
4,459519,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,1876222,24,8,8,6
8,1427444,24,9,8,6
9,759419,24,10,8,6

In [8]:
%%sql
select customerkey, count(quantity) as total_quantity,
row_number() over (order by count(quantity) desc) as total_quantity_rownum,
rank() over (order by count(quantity) desc) as total_quantity_rank,
dense_rank() over (order by count(quantity) desc) as total_quantity_dense_rank

from sales
group by customerkey
order by total_quantity desc
limit 30

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

30 rows affected.

,customerkey,total_quantity,total_quantity_rownum,total_quantity_rank,total_quantity_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6
10,2079681,22,11,11,7
11,578215,22,12,11,7
12,1743963,22,13,11,7
13,1780427,22,14,11,7
14,1496962,22,15,11,7
15,1552351,21,16,16,8
16,1390742,21,17,16,8
17,1071231,21,18,16,8
18,1289648,21,19,16,8
19,1295351,21,20,16,8
20,2032301,21,21,16,8
21,1481672,21,22,16,8
22,399184,21,23,16,8
23,375982,21,24,16,8
24,1764902,21,25,16,8
25,343451,21,26,16,8
26,2059525,21,27,16,8
27,1975724,21,28,16,8
28,433710,20,29,29,9
29,1532987,20,30,29,9

In [14]:
%%sql
--lag and lead, first_value, last value, nth value
--note; last month will not work until you use unbounding preceding and unfollow
WITH monthly_rev AS (select
to_char(orderdate, 'YYYY-MM') as order_month,
sum(quantity * netprice * exchangerate) as net_rev
from sales
where extract(year from orderdate) = 2023
group by order_month
order by order_month)

select
*,
first_value(net_rev) over (order by order_month) as first_month_rev,
last_value(net_rev) over (order by order_month rows between unbounded preceding and unbounded following) as last_month_rev,
nth_value(net_rev, 3) over (order by order_month rows between unbounded preceding and unbounded following) as third_month_rev
from monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   order_month    net_rev  first_month_rev  last_month_rev  third_month_rev
0      2023-01 3664431.34       3664431.34      2928550.93       2244316.52
1      2023-02 4465204.57       3664431.34      2928550.93       2244316.52
2      2023-03 2244316.52       3664431.34      2928550.93       2244316.52
3      2023-04 1162796.16       3664431.34      2928550.93       2244316.52
4      2023-05 2943005.99       3664431.34      2928550.93       2244316.52
5      2023-06 2864500.03       3664431.34      2928550.93       2244316.52
6      2023-07 2337639.34       3664431.34      2928550.93       2244316.52
7      2023-08 2623919.79       3664431.34      2928550.93       2244316.52
8      2023-09 2622774.85       3664431.34      2928550.93       2244316.52
9      2023-10 2551322.61       3664431.34      2928550.93       2244316.52
10     2023-11 2700103.38       3664431.34      2928550.93       2244316.52
11     2023-12 2928550.93       3664431.34      2928550.93       2244316.52

In [15]:
%%sql
WITH monthly_rev AS (select
to_char(orderdate, 'YYYY-MM') as order_month,
sum(quantity * netprice * exchangerate) as net_rev
from sales
where extract(year from orderdate) = 2023
group by order_month
order by order_month)

select
*,
LAG(net_rev) OVER (ORDER BY order_month) AS previous_month_rev,
LEAD(net_rev) OVER (ORDER BY order_month) AS next_month_rev
FROM monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   order_month    net_rev  previous_month_rev  next_month_rev
0      2023-01 3664431.34                 NaN      4465204.57
1      2023-02 4465204.57          3664431.34      2244316.52
2      2023-03 2244316.52          4465204.57      1162796.16
3      2023-04 1162796.16          2244316.52      2943005.99
4      2023-05 2943005.99          1162796.16      2864500.03
5      2023-06 2864500.03          2943005.99      2337639.34
6      2023-07 2337639.34          2864500.03      2623919.79
7      2023-08 2623919.79          2337639.34      2622774.85
8      2023-09 2622774.85          2623919.79      2551322.61
9      2023-10 2551322.61          2622774.85      2700103.38
10     2023-11 2700103.38          2551322.61      2928550.93
11     2023-12 2928550.93          2700103.38             NaN

In [18]:
%%sql
--month by month revenue changes or differenxce. also percentage change
WITH monthly_rev AS (select
to_char(orderdate, 'YYYY-MM') as order_month,
sum(quantity * netprice * exchangerate) as net_rev
from sales
where extract(year from orderdate) = 2023
group by order_month
order by order_month)

select
*,
LAG(net_rev) OVER (ORDER BY order_month) AS previous_month_rev,
net_rev - LAG(net_rev) OVER (ORDER BY order_month) AS monthly_rev,
100*(net_rev - LAG(net_rev) OVER (ORDER BY order_month))/LAG(net_rev) OVER (ORDER BY order_month) AS percentage_change
FROM monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   order_month    net_rev  previous_month_rev  monthly_rev  percentage_change
0      2023-01 3664431.34                 NaN          NaN                NaN
1      2023-02 4465204.57          3664431.34    800773.22              21.85
2      2023-03 2244316.52          4465204.57  -2220888.05             -49.74
3      2023-04 1162796.16          2244316.52  -1081520.36             -48.19
4      2023-05 2943005.99          1162796.16   1780209.83             153.10
5      2023-06 2864500.03          2943005.99    -78505.96              -2.67
6      2023-07 2337639.34          2864500.03   -526860.69             -18.39
7      2023-08 2623919.79          2337639.34    286280.45              12.25
8      2023-09 2622774.85          2623919.79     -1144.94              -0.04
9      2023-10 2551322.61          2622774.85    -71452.24              -2.72
10     2023-11 2700103.38          2551322.61    148780.78               5.83
11     2023-12 2928550.93          2700103.38    228447.54               8.46

In [26]:
%%sql
--FRAME CLAUSEs
--rows and current row
--preceding and following

WITH monthly_rev AS (select
to_char(orderdate, 'YYYY-MM') as month,
sum(quantity * netprice * exchangerate) as net_rev
from sales
where extract(year from orderdate) = 2023
group by month
order by month)
select
month, net_rev,
avg(net_rev) over (order by month rows between current row and current row) as current_month_avg,
avg(net_rev) over (order by month rows between 1 preceding and current row) as previous_month_avg,
avg(net_rev) over (order by month rows between 1 preceding and 1 following) as previous_and_next_month_avg
from monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_rev,current_month_avg,previous_month_avg,previous_and_next_month_avg
0,2023-01,3664431.34,3664431.34,3664431.34,4064817.96
1,2023-02,4465204.57,4465204.57,4064817.96,3457984.14
2,2023-03,2244316.52,2244316.52,3354760.54,2624105.75
3,2023-04,1162796.16,1162796.16,1703556.34,2116706.22
4,2023-05,2943005.99,2943005.99,2052901.08,2323434.06
5,2023-06,2864500.03,2864500.03,2903753.01,2715048.45
6,2023-07,2337639.34,2337639.34,2601069.68,2608686.39
7,2023-08,2623919.79,2623919.79,2480779.57,2528111.33
8,2023-09,2622774.85,2622774.85,2623347.32,2599339.08
9,2023-10,2551322.61,2551322.61,2587048.73,2624733.61
10,2023-11,2700103.38,2700103.38,2625712.99,2726658.97
11,2023-12,2928550.93,2928550.93,2814327.15,2814327.15

In [27]:
%%sql
--ubounding preceding and ubounding following
WITH monthly_rev AS (select
to_char(orderdate, 'YYYY-MM') as month,
sum(quantity * netprice * exchangerate) as net_rev
from sales
where extract(year from orderdate) = 2023
group by month
order by month)
select
month, net_rev,
avg(net_rev) over (order by month rows between unbounded preceding and unbounded following) as unbounded_avg,
avg(net_rev) over (order by month rows between unbounded preceding and current row) as unbounded_preceding_avg
from monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month    net_rev  unbounded_avg  unbounded_preceding_avg
0   2023-01 3664431.34     2759047.13               3664431.34
1   2023-02 4465204.57     2759047.13               4064817.96
2   2023-03 2244316.52     2759047.13               3457984.14
3   2023-04 1162796.16     2759047.13               2884187.15
4   2023-05 2943005.99     2759047.13               2895950.92
5   2023-06 2864500.03     2759047.13               2890709.10
6   2023-07 2337639.34     2759047.13               2811699.14
7   2023-08 2623919.79     2759047.13               2788226.72
8   2023-09 2622774.85     2759047.13               2769843.18
9   2023-10 2551322.61     2759047.13               2747991.12
10  2023-11 2700103.38     2759047.13               2743637.69
11  2023-12 2928550.93     2759047.13               2759047.13

# Task
The goal is to explain and demonstrate the use of `ROW_NUMBER()` and `RANK()` window functions in SQL, highlighting their differences, particularly in how they handle ties. This will involve providing a detailed explanation and then practical SQL examples using the `sales` table from the `contoso_100k` database.

## Explain ROW_NUMBER() and RANK()

### Subtask:
Provide a detailed explanation of `ROW_NUMBER()` and `RANK()` window functions, focusing on their behavior with ties.

### Explain ROW_NUMBER() and RANK()

### Subtask:
Provide a detailed explanation of `ROW_NUMBER()` and `RANK()` window functions, focusing on their behavior with ties.

#### ROW_NUMBER()

`ROW_NUMBER()` is a window function that assigns a unique, sequential integer to each row within its partition, starting from 1. The numbering is based on the `ORDER BY` clause specified within the `OVER()` clause.

**Behavior with Ties:** `ROW_NUMBER()` does not account for ties. Even if two or more rows have identical values in the columns specified in the `ORDER BY` clause, `ROW_NUMBER()` will assign a unique, consecutive integer to each of them. It effectively treats every row as distinct for ranking purposes, regardless of value equality.

#### RANK()

`RANK()` is a window function that assigns a rank to each row within its partition, based on the ordering of the rows defined by the `ORDER BY` clause.

**Behavior with Ties:** `RANK()` handles ties by assigning the same rank to rows that have identical values in the columns specified in the `ORDER BY` clause. After assigning the same rank to tied rows, it skips the subsequent ranks. For example, if three rows are tied for rank 1, the next distinct rank would be 4 (1, 1, 1, 4, 5...). This creates gaps in the ranking sequence.

#### Key Difference

The fundamental difference lies in their treatment of ties:
- `ROW_NUMBER()` always assigns a unique number to each row, even if they have identical values, resulting in no gaps in the numbering sequence.
- `RANK()` assigns the same rank to tied rows and then skips ranks, creating gaps in the ranking sequence.

## Demonstrate with SQL Examples

### Subtask:
Create SQL queries using the `sales` table to illustrate the practical difference between `ROW_NUMBER()` and `RANK()` with examples that include potential ties.

## Summary:

### Data Analysis Key Findings

*   `ROW_NUMBER()` assigns a unique, sequential integer to each row within its partition, beginning from 1, based on the `ORDER BY` clause. It does not account for ties; even if values are identical, it assigns distinct numbers, ensuring no gaps in the numbering sequence.
*   `RANK()` assigns the same rank to rows with identical values in the `ORDER BY` clause within its partition. It then skips subsequent ranks, thereby creating gaps in the ranking sequence (e.g., if three rows are tied for rank 1, the next distinct rank would be 4).
*   The primary distinction between the two functions lies in their handling of ties: `ROW_NUMBER()` guarantees a unique number for every row without gaps, whereas `RANK()` assigns identical ranks to tied rows and introduces gaps in the rank sequence.

### Insights or Next Steps

*   The next step will involve creating practical SQL examples using the `sales` table to visually demonstrate these differences, especially how `ROW_NUMBER()` and `RANK()` behave with ties.